# App name
spring.application.name=standup-iq
spring.config.import=optional:file:.env[.properties]

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/standupiq
spring.datasource.username=standupuser
spring.datasource.password=standup123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Spring Security for now (we'll add it back later)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Server port
server.port=8080

github.token=${GITHUB_TOKEN}
github.api.base-url=https://api.github.com
